---
title: "Class Analysis for LING 343"
author: "Lisa Levinson"
date: 2023-03-30
format: 
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("analysis/class_analysis.qmd")
library(here)
library(tidyverse)
```

# Read in Data

Create dataframes from the three rds files in the data folder. 

# Participant Accuracy Check

For each participant, get percent accuracy for comprehension questions.

# Combine Stimuli Information

Add the information about each stimulus sentence from the stimuli file to
the self-paced reading data. They should have matching label variables.

## Count Stimuli Per Condition

The first condition column in the stimuli labels the experiment. For 
the experiment labelled "gp", how many stimuli are there per condition?

How many stimuli are there per item?

Answer these questions for the "mklo" stimuli. 


# McKoon and Love 2011 Replication

The "mklo" stimuli are from the study McKoon and Love 2011. They found
that result ("break") verbs had longer reaction times than manner ("hit") verbs.
The verb is the third word in each sentence. Was their effect replicated in
this experiment? Let's take some steps to see.

McKoon, G., & Love, J. (2011). Verbs in the lexicon: Why is hitting easier than breaking? Language and Cognition, 3, 313–330. <https://doi.org/10.1515/LANGCOG.2011.011>


## Summaries 

For visualization and basic summary statistics, where participants are exposed 
to repeated measures, we usually calculate averages for each participant first. 
We want the average
for each participant for each condition, so averaging "over" all of the items
they saw in that condition. But remember we want to separate the times for each
word, and we are mainly interested in the verb (word 3).

Then, we average those averages to get a condition mean. Did break verbs
take longer than hit verbs?

Try printing your output as a formatted table by piping the dataframe/tibble
to the function `kableExtra::kbl()`. You may need to first install the
package `{kableExtra}` from CRAN. 

## Plots

Make a plot showing the means for both conditions for word 3. 

Now add words 2 and 4 also. Can you put them in one faceted plot?

# Gennari and Poeppel 2003 Replication

The "gp" stimuli are from the study Gennari and Poeppel 2003. They found 
that eventive verbs had longer RTs than stative verbs. The verb is the fourth
word in these sentences. Was their effect replicated? Try the same steps. 

Gennari, S., & Poeppel, D. (2003). Processing correlates of lexical semantic complexity. Cognition, 89(1), B27–B41. <https://doi.org/10.1016/S0010-0277(03)00069-6>


## Summaries

## Plots